version: '3.7'

services:
    mysql:
        container_name: video_catalog_admin_mysql
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=video_catalog_admin
        security_opt:
            -   seccomp:unconfined
        ports:
            - 3306:3306
        networks:
            - video_catalog_admin_network

networks:
    video_catalog_admin_network: